---
name: korbis-external-deps
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.2
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./weaviate_data:/var/lib/weaviate
    - ./weaviate_backups:/tmp/backups
    restart: on-failure:0
    environment:
      CLIP_INFERENCE_API: 'http://multi2vec-clip:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'xxxxxxxxxxxxxxxx_myapikey_xxxxxxxxxxxxxxxx'
      AUTHENTICATION_APIKEY_USERS: 'service-account'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'multi2vec-clip'
      ENABLE_MODULES: 'backup-filesystem,multi2vec-clip'
      CLUSTER_HOSTNAME: 'node1'
      BACKUP_FILESYSTEM_PATH: '/tmp/backups'
      AUTOSCHEMA_ENABLED: 'false'
  multi2vec-clip:
    image: cr.weaviate.io/semitechnologies/multi2vec-clip:sentence-transformers-clip-ViT-B-32-multilingual-v1
    environment:
      ENABLE_CUDA: '0'
  weaviate-ui:
    image: naaive/weaviate-ui:latest
    restart: unless-stopped
    ports:
      - 7777:7777
    environment:
      WEAVIATE_URL: http://host.docker.internal:8080
      WEAVIATE_API_KEYS: 'xxxxxxxxxxxxxxxx_myapikey_xxxxxxxxxxxxxxxx'
    depends_on:
      - weaviate
...