name: Deploy Supabase

on:
  push:
    branches:
      - 'main'
    paths: 
      - 'sb-backend-app/supabase/**'
  workflow_dispatch:

jobs:
  sbdeploy:
    name: Deploy Supabase Functions
    runs-on: ubuntu-latest
    timeout-minutes: 15

    concurrency:
      group: supabase-deploy-${{ github.ref }}
      cancel-in-progress: true

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
        working-directory: sb-backend-app